In [1]:
import numpy as np

In [2]:
num=np.array([1,2,3,4])

In [3]:
print(num)

[1 2 3 4]


In [4]:
num.shape

(4,)

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
a.shape

(2, 4)

In [8]:
a.T #transpose

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
b=np.array([[1,2],[4,5],[7,6],[9,6]])

In [12]:
x=np.dot(a,b) #dot product of a and b

In [11]:
print(x)

[[ 66  54]
 [150 130]]


In [21]:
mini=np.min(a)

In [22]:
mini=np.min(x)
print(mini)

54


In [16]:
mat=np.random.randint(50,100,10) #generate 10 random integer between 61&99

In [17]:
print(mat)

[75 81 84 60 94 51 82 90 76 73]


In [18]:
matrix=np.random.randint(50,100,(5,5))
print(matrix)

[[95 60 96 57 69]
 [98 92 53 84 81]
 [64 64 68 60 83]
 [90 73 96 89 85]
 [51 76 87 96 59]]


In [20]:
print(np.min(matrix))

51


In [23]:
print(np.max(matrix))

98


In [24]:
idx=np.argmin(matrix)
print(idx)

20


In [25]:
arr=np.random.randint(60,100,10)
print(arr)

[72 76 60 78 89 76 87 72 90 82]


In [26]:
idx=np.argmin(arr)
print(idx)

2


In [27]:
b=np.unique(arr)
print(b)

[60 72 76 78 82 87 89 90]


In [31]:
b=np.unique(arr,return_counts=True) #array of unique elements followed by  array of count of elements
print(b)

(array([60, 72, 76, 78, 82, 87, 89, 90]), array([1, 2, 2, 1, 1, 1, 1, 1], dtype=int64))


In [34]:
idx=np.argmax(b[1])#index of min element from count array
print(b[0][idx]) #element of highest freq

72
